<a href="https://colab.research.google.com/github/didara1234/first_gomycode_code/blob/main/checkpoint2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
mylist=[]
for x in range(2000,3200,1):
  if ((x%7 == 0) and (x%5 != 0)):
    mylist.append(x)
print(mylist)   
    

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [ ]:
x =int(input())
y =1 
while x>0:
  y = y * x
  x-=1
print(y) 

5
120


In [ ]:
x = int(input())
y=1
dictionary={}
for x in range (y,x+1):
  dictionary[y]=y*y
  y+=1
print(dictionary) 

5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
x =input()
list1=[]
for y in x:
  list1.append(y)
print(list1)
c = int(input())
del list1 [c]
print(list1)

kitten
['k', 'i', 't', 't', 'e', 'n']
2
['k', 'i', 't', 'e', 'n']


In [ ]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)
list1 = b.tolist()
print(list1)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]


In [ ]:
import numpy as np
array1=np.array([2,1,0])
array2=np.array([0,1,2])
x = np.cov(array1,array2)
print(x)

[[ 1. -1.]
 [-1.  1.]]


In [6]:
import numpy as np
import math
list1 = []
c = 50
h = 30
d = input().split(",")

for d in d:
  Q = math.sqrt((2*c*int(d))/h)
  list1.append(math.floor(Q))
print(list1)

100,150,180
[18, 22, 24]
